<?php
namespace Seaf\Core\Loader;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-06 at 07:38:44.
 */
class AutoLoaderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AutoLoader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AutoLoader;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Seaf\Core\Loader\AutoLoader::init
     * @todo   Implement testInit().
     */
    public function testInit()
    {
        $object = AutoLoader::init();
        $hash = spl_object_hash($object);

        $object2 = AutoLoader::init();
        $hash2 = spl_object_hash($object2);

        $this->assertEquals($hash, $hash2);
        $this->assertInstanceOf(__NAMESPACE__.'\\AutoLoader', $object);
    }

    /**
     * @covers Seaf\Core\Loader\AutoLoader::addLibraryPath
     * @todo   Implement testAddLibraryPath().
     */
    public function testAddLibraryPath()
    {
        $this->assertEquals(1, $this->object->addLibraryPath('/'));
        $this->assertEquals(1, $this->object->addLibraryPath('/'));
        $this->assertEquals(2, $this->object->addLibraryPath('/lib'));
    }

    /**
     * @covers Seaf\Core\Loader\AutoLoader::addNamespace
     * @todo   Implement testAddNamespace().
     */
    public function testAddNamespace()
    {
        $this->assertEquals(1, $this->object->addNamespace(
            'Seaf\Core\Loader',
            null,
            '/project/seaf/core/src/Core/Loader'
        ));
    }

    /**
     * @covers Seaf\Core\Loader\AutoLoader::library
     * @todo   Implement testLibrary().
     */
    public function testLibrary()
    {
        $this->object->addLibraryPath(
            '/project/seaf/core/src'
        );

        $file = $this->object->library('Core\Loader\NameSpaceListIterator', true);

        $this->assertEquals(
            '/project/seaf/core/src/Core/Loader/NameSpaceListIterator.php',
            $file
        );
    }

    /**
     * @covers Seaf\Core\Loader\AutoLoader::seaf
     * @todo   Implement testSeaf().
     */
    public function testSeaf()
    {
        $this->object->addNamespace(
            'Seaf\Core\Loader',
            null,
            '/project/seaf/core/src/Core/Loader'
        );

        $file = $this->object->seaf('Seaf\Core\Loader\NameSpaceListIterator', true);

        $this->assertEquals(
            '/project/seaf/core/src/Core/Loader/NameSpaceListIterator.php',
            $file
        );
    }
}
