<?php
namespace Seaf\Core\Loader;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-06 at 07:26:54.
 */
class NameSpaceListIteratorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var NameSpaceListIterator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new NameSpaceListIterator ( 
            array(
                array(
                    'ns'      => 'Some\Name\Space',
                    'scripts' => array(),
                    'path'    => './src'
                ),
                array(
                    'ns'      => 'Some\Name\Space',
                    'scripts' => array(),
                    'path'    => './src2'
                )
            ),
            'Some\Name\Space\TestClass'
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Seaf\Core\Loader\NameSpaceListIterator::rewind
     * @todo   Implement testRewind().
     */
    public function testRewind()
    {
        $this->object->rewind( );
    }

    /**
     * @covers Seaf\Core\Loader\NameSpaceListIterator::valid
     * @todo   Implement testValid().
     */
    public function testValid()
    {
        $this->object->valid( );
    }

    /**
     * @covers Seaf\Core\Loader\NameSpaceListIterator::current
     * @todo   Implement testCurrent().
     */
    public function testCurrent()
    {
        $this->object->rewind();
        $this->assertEquals('./src',$this->object->current());
    }

    /**
     * @covers Seaf\Core\Loader\NameSpaceListIterator::key
     * @todo   Implement testKey().
     */
    public function testKey()
    {
        $this->object->rewind();
        $this->assertEquals('Some\Name\Space',$this->object->key());
    }

    /**
     * @covers Seaf\Core\Loader\NameSpaceListIterator::next
     * @todo   Implement testNext().
     */
    public function testNext()
    {
        $this->object->rewind();
        $this->assertEquals('./src',$this->object->current());

        $this->object->next();
        $this->assertEquals('./src2',$this->object->current());
    }
}
