<?php
namespace Seaf\Core\Factory;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-06 at 08:31:15.
 */
class FactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Factory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Factory;
        $this->object->register('factory', __NAMESPACE__.'\\Factory');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Seaf\Core\Factory\Factory::set
     * @todo   Implement testSet().
     */
    public function testSet()
    {
        $this->object->set('factory2', __NAMESPACE__.'\\Factory');
    }

    /**
     * @covers Seaf\Core\Factory\Factory::register
     * @todo   Implement testRegister().
     */
    public function testRegister()
    {
        $this->object->register('factory2', __NAMESPACE__.'\\Factory');
    }

    /**
     * @covers Seaf\Core\Factory\Factory::create
     * @todo   Implement testCreate().
     */
    public function testCreate()
    {
        $this->assertInstanceOf(
            __NAMESPACE__.'\\Factory',
            $this->object->create('factory')
        );
    }
}
