<?php
namespace Seaf\Core\DI;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-06 at 08:20:00.
 */
class DIContainerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DIContainer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DIContainer( );
        $this->object->register('di', __NAMESPACE__.'\\DIContainer');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Seaf\Core\DI\DIContainer::register
     * @todo   Implement testRegister().
     */
    public function testRegister()
    {
        $waik = false;
        $this->object->register('name', __NAMESPACE__.'\\DIContainer', function( ) use (&$waik) {
            $waik = true;
        });

        $this->object->get('name');

        $this->assertTrue($waik);
    }

    /**
     * @covers Seaf\Core\DI\DIContainer::has
     * @todo   Implement testHas().
     */
    public function testHas()
    {
        $this->assertTrue($this->object->has('di'));
        $this->assertFalse($this->object->has('no'));
    }

    /**
     * @covers Seaf\Core\DI\DIContainer::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        $this->assertInstanceOf(
            'Seaf\Core\DI\DIContainer',
            $this->object->get('di')
        );
    }

    /**
     * @covers Seaf\Core\DI\DIContainer::__invoke
     * @todo   Implement test__invoke().
     */
    public function test__invoke()
    {
        $this->assertInstanceOf(
            'Seaf\Core\DI\DIContainer',
            $this->object->__invoke('di')
        );

        $object = $this->object;
        $this->assertInstanceOf(
            'Seaf\Core\DI\DIContainer',
            $object('di')
        );
    }
}
