<?php
namespace Seaf\Core\Environment\Component;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-06 at 09:03:51.
 */
class EventTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Event
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Event;
        $this->object->on('test',function() {
            return 'test';
        });

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Seaf\Core\Environment\Component\Event::on
     * @todo   Implement testOn().
     */
    public function testOn()
    {
        $str = '';

        $this->object->on('testing',function() use(&$str) {
            $str = 'testing';
        });

        $this->object->trigger('testing');

        $this->assertEquals('testing', $str);
    }

    /**
     * @covers Seaf\Core\Environment\Component\Event::off
     * @todo   Implement testOff().
     */
    public function testOff()
    {
        $str = '';
        $this->object->on('testing',$func = function() use(&$str){
            $str = 'testing';
        });

        $this->object->trigger('testing');

        $this->assertEquals('testing', $str);
        $str = '';
        $this->object->off('testing', $func);
        $this->object->trigger('testing');
        $this->assertEquals('', $str);
    }

    /**
     * @covers Seaf\Core\Environment\Component\Event::trigger
     * @todo   Implement testTrigger().
     */
    public function testTrigger()
    {
        $int = 0;
        $this->object->on('testing',$func = function($n1, $n2) use(&$int){
            $int = $n1 * $n2;
        });

        $this->object->trigger('testing', 10, 20);

        $this->assertEquals(200,$int);
    }
}
